# Generated by Django 4.1.5 on 2023-01-31 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='House',
            new_name='House2',
        ),
    ]
